---
- hosts: all
  #  become: true
  tasks:

  - name: remove docker images before new build
    command: docker rmi simple-devops-image:latest bhanukarandeniya/simple-devops-image
    ignore_errors: yes

  - name: build docker image
    command: docker build -t simple-devops-image .
    args:
      chdir: /opt/docker-images
      
  - name: tag docker image for docker repository push
    command: docker tag simple-devops-image:latest bhanukarandeniya/simple-devops-image

  - name: push the image to the repository
    command: docker push bhanukarandeniya/simple-devops-image

